ai_agent:
  growth_factor: 1.1
  temporal_adjustment: 1.0

ui:
  primary_color: "#0d6efd"
  accent_color: "#6610f2"
  font_family: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif"
  background_color: "#f5f7fa"
  secondary_background_color: "#e9ecef"
