[theme]
base="light"
primaryColor="#1f77b4"
secondaryBackgroundColor="#f0f2f6"
font="sans serif"

[server]
headless = true
enableCORS = false
port = 8501
enableXsrfProtection = false

[client]
showSidebarNavigation = true
toolbarMode = "minimal"
